// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TennisTime.Models;

namespace TennisTime.Migrations
{
    [DbContext(typeof(RacquetContext))]
    [Migration("20211114192148_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TennisTime.Models.Make", b =>
                {
                    b.Property<string>("MakeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MakeId");

                    b.ToTable("Make");

                    b.HasData(
                        new
                        {
                            MakeId = "W",
                            Name = "Wilson"
                        },
                        new
                        {
                            MakeId = "B",
                            Name = "Babolat"
                        },
                        new
                        {
                            MakeId = "Y",
                            Name = "Yonex"
                        });
                });

            modelBuilder.Entity("TennisTime.Models.Racquet", b =>
                {
                    b.Property<int>("RacquetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MakeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Price")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("RacquetId");

                    b.HasIndex("MakeId");

                    b.ToTable("Racquets");

                    b.HasData(
                        new
                        {
                            RacquetId = 1,
                            MakeId = "A",
                            Model = "Blade 98 v7",
                            Price = "200",
                            Year = 2020
                        },
                        new
                        {
                            RacquetId = 2,
                            MakeId = "A",
                            Model = "Pro Staff",
                            Price = "200",
                            Year = 2018
                        },
                        new
                        {
                            RacquetId = 3,
                            MakeId = "B",
                            Model = "Aero Pro Drive",
                            Price = "180",
                            Year = 2019
                        },
                        new
                        {
                            RacquetId = 4,
                            MakeId = "C",
                            Model = "Vcore 98",
                            Price = "200",
                            Year = 2021
                        });
                });

            modelBuilder.Entity("TennisTime.Models.Racquet", b =>
                {
                    b.HasOne("TennisTime.Models.Make", "Make")
                        .WithMany()
                        .HasForeignKey("MakeId");

                    b.Navigation("Make");
                });
#pragma warning restore 612, 618
        }
    }
}
